# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CD

on:
  push:
    branches: [ main ]
env:
  PORT: ${{secrets.API_PORT}}
  TS3_HOST: ${{secrets.TS3_HOST}}
  TS3_SERVER_PORT: ${{secrets.TS3_PORT}}
  TS3_QUERY_PORT: ${{secrets.TS3_QUERY_PORT}}
  TS3_USER: ${{secrets.TS3_USER}}
  TS3_PASS: ${{secrets.TS3_PASS}}
  TS3_NICK: ${{secrets.TS3_NICK}}
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - uses: chrnorm/deployment-action@releases/v1
      name: Create GitHub deployment
      id: deployment
      with:
        token: "${{ github.token }}"
        target_url: https://tsapi.n1eko.com/
        environment: production
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create env file
      run: |
          touch .env
          echo PORT=${{ secrets.API_PORT }} >> .env
          echo TS3_HOST=${{ secrets.TS3_HOST }} >> .env
          echo TS3_SERVER_PORT=${{ secrets.TS3_PORT }} >> .env
          echo TS3_QUERY_PORT=${{ secrets.TS3_QUERY_PORT }} >> .env
          echo TS3_USER=${{ secrets.TS3_USER }} >> .env
          echo TS3_PASS=${{ secrets.TS3_PASS }} >> .env
          echo TS3_NICK=${{ secrets.TS3_NICK }} >> .env
    - run: npm install
    - run: pm2 restart TS3API
    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        target_url: https://tsapi.n1eko.com/
        state: "success"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}

    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        target_url: https://tsapi.n1eko.com/
        state: "failure"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
